PR #1
m1st0rm/innowise_task_1 pull request #1
Opened 2024-09-05 12:39 UTC by m1st0rm

@IvanNikalayeu

2024-09-17 11:33 UTC, IvanNikalayeu requested changes

2024-09-17 14:56 UTC, m1st0rm commented on json_parser.py
> +"""
Если убрать докстринги, логирование и различные проверки валидности данных, то останется совсем немного кода, так что: ИМХО такая реализация приемлема

2024-09-18 06:22 UTC, m1st0rm commented on .gitignore
Done

2024-09-18 08:42 UTC, m1st0rm commented on main.py
> +import argparse
Done

2024-10-04 12:44 UTC, merged